[package]
name = "bit_torrent"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
rand = "0.9.2"
reqwest = { version = "0.12.24", features = ["blocking"] }
sha1 = "0.10.6"
tokio = { version = "1.48.0", features = ["full"] }
url = "2.5.7"
urlencoding = "2.1.3"
