version: '3.8'

services:
  seeder:
    image: linuxserver/transmission
    container_name: bt_seeder
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TRANSMISSION_DOWNLOAD_DIR=/downloads
      - TRANSMISSION_RPC_ENABLED=true
      - TRANSMISSION_RPC_PORT=9091
    volumes:
      - ./torrent_files:/downloads
    ports:
      - "51413:51413"      # TCP BitTorrent port
      - "51413:51413/udp"  # UDP DHT port
      - "9091:9091"        # Web UI
    restart: unless-stopped
